### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: setParameters failed

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-android#30]
https://fabric.io/klub-jagiellonski/android/apps/pl.pola_app/issues/5986010dbe077a4dcca7d1c2?time=last-seven-days
```
Fatal Exception: java.lang.RuntimeException: setParameters failed
       at android.hardware.Camera.native_setParameters(Camera.java)
       at android.hardware.Camera.setParameters(Camera.java:1707)
       at pl.pola_app.helpers.OldCamera.open(OldCamera.java:44)
       at pl.pola_app.ui.fragment.VideoCaptureFragment.onViewCreated(VideoCaptureFragment.java:117)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5257)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by gkapusta** [comment]
Poprawione w https://github.com/KlubJagiellonski/pola-android/commit/985a37351f7e642d13dc2110a226b1a80f0cb85a

**Comment by jakublipinski** [comment]
Zamknięte w `1.6`
