### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=172, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {pl.pola_app/pl.pola_app.ui.activity.CreateReportActivity}: java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list U:content://pl.pola_app.easyphotopicker.fileprovider/picturesext/bf506ace-2cb2-4e80-b570-ecc37000c0d5-615338898.jpg} (has extras) } from ProcessRecord{8e28f2 25202:pl.pola_app/u0a245} (pid=25202, uid=10245) with revoked permission android.permission.CAMERA

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-android#31]
https://fabric.io/klub-jagiellonski/android/apps/pl.pola_app/issues/59858f6cbe077a4dcca37806?time=last-seven-days
```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=172, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {pl.pola_app/pl.pola_app.ui.activity.CreateReportActivity}: java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list U:content://pl.pola_app.easyphotopicker.fileprovider/picturesext/bf506ace-2cb2-4e80-b570-ecc37000c0d5-615338898.jpg} (has extras) } from ProcessRecord{8e28f2 25202:pl.pola_app/u0a245} (pid=25202, uid=10245) with revoked permission android.permission.CAMERA
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3714)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3757)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5468)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)
Caused by java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list U:content://pl.pola_app.easyphotopicker.fileprovider/picturesext/bf506ace-2cb2-4e80-b570-ecc37000c0d5-615338898.jpg} (has extras) } from ProcessRecord{8e28f2 25202:pl.pola_app/u0a245} (pid=25202, uid=10245) with revoked permission android.permission.CAMERA
       at android.os.Parcel.readException(Parcel.java:1599)
       at android.os.Parcel.readException(Parcel.java:1552)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2715)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1510)
       at android.app.Activity.startActivityForResult(Activity.java:3930)
       at android.app.Activity.startActivityForResult(Activity.java:3890)
       at pl.aprilapps.easyphotopicker.EasyImage.openCamera(EasyImage.java:231)
       at pl.pola_app.ui.activity.CreateReportActivity$6.permissionGranted(CreateReportActivity.java:395)
       at pl.tajchert.nammu.Nammu.onRequestPermissionsResult(Nammu.java:97)
       at pl.pola_app.ui.activity.CreateReportActivity.onRequestPermissionsResult(CreateReportActivity.java:406)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6582)
       at android.app.Activity.dispatchActivityResult(Activity.java:6460)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3710)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3757)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5468)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)
```

**Comment by gewaraz** [comment]
Pozwolicie, że ja to wezmę ;)

**Comment by jakublipinski** [comment]
Śmiało :)

**Comment by jakublipinski** [comment]
Jak zrobisz dzisiaj to jeszcze wciągniemy do `1.6` :)

**Comment by gewaraz** [comment]
Zaraz coś doślę

**Comment by gewaraz** [comment]
https://github.com/KlubJagiellonski/pola-android/pull/39

**Comment by jakublipinski** [comment]
Zamknięte w `1.6`
