### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Camera is being used after Camera.release() was called

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-android#32]
https://fabric.io/klub-jagiellonski/android/apps/pl.pola_app/issues/59861d35be077a4dcca8ca3d?time=last-seven-days
```
Fatal Exception: java.lang.RuntimeException: Camera is being used after Camera.release() was called
       at android.hardware.Camera.setPreviewSurface(Camera.java)
       at android.hardware.Camera.setPreviewDisplay(Camera.java:654)
       at pl.pola_app.helpers.OldCamera.openPreview(OldCamera.java:52)
       at pl.pola_app.ui.fragment.VideoCaptureFragment.surfaceCreated(VideoCaptureFragment.java:129)
       at android.view.SurfaceView.updateWindow(SurfaceView.java:580)
       at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:238)
       at android.view.View.dispatchWindowVisibilityChanged(View.java:8861)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1165)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1322)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1065)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5901)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5389)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```

**Comment by gkapusta** [comment]
Poprawione w https://github.com/KlubJagiellonski/pola-android/commit/56ee9f82b0c2a9dd44d69d67d0b3856bf016172b

**Comment by jakublipinski** [comment]
Zamknięte w `1.6`
