### ISSUE TITLE
Podniesienie wersji bibliotek aplikacji

### ISSUE THREAD

**Issue by rafalgawlik** [KlubJagiellonski/pola-android#70]

**Comment by karkaminski** [comment]
Cześć! Chciałbym rozwiązać to issue z okazji hacktoberfest :) czy można?

**Comment by WezSieTato** [comment]
Śmiało :)

**Comment by karkaminski** [comment]
Nie wiem, czemu mi ten PR failuje :( jestem noobem w CI. Mógłby mnie ktoś naprowadzić gdzie popełniam błąd? Może za bardzo się rozpędziłem z tym podnoszeniem bibliotek? ;) U mnie testy `pl.pola_app.ui.activity.MainPresenterTest` przechodzą

**Comment by rafalgawlik** [comment]
Zasadniczo przy PRkach trzymany jest pewien skrypt budowania. Warto u siebie lokalnie zobaczyć co się dzieje jak się go wywoła.

Z tego co widzę, to jest taki error:
`The command "./gradlew clean test -Pbuild=dev" exited with 1.`

zobacz lokalnie co wyskakuje jak wywołaniu
`./gradlew clean test -Pbuild=dev`

**Comment by rafalgawlik** [comment]
@karkaminski jak będziesz miał jakieś rezultaty to daj znać, coś zaradzimy :)

**Comment by karkaminski** [comment]
Log z raportu:


**MainPresenterTest. testCallCanceledOnUnregister**

```
java.lang.NullPointerException
	at pl.pola_app.ui.activity.MainPresenter.onBarcode(MainPresenter.java:110)
	at pl.pola_app.ui.activity.MainPresenterTest.testCallCanceledOnUnregister(MainPresenterTest.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by rafalgawlik** [comment]
A widzisz. I to już wiele mówi. ;)

**Comment by rafalgawlik** [comment]
Coś po podbiciu bibliotek nie styka na: `MainPresenter.java w linii 110`
Można zobaczyć co tam nie styka i zaniechać aktualizacji niestykającej biblioteki albo spróbować naprawić błąd. Przy czasie sam na to spojrzę. :)

Ihmo kod jest nieco zaniedbany, dopiero teraz ruszamy z odświeżeniem.
